# Generated by Django 3.1.3 on 2020-11-07 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0006_auto_20201107_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snake',
            name='card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snakes.snakecard'),
        ),
        migrations.AlterField(
            model_name='snakecard',
            name='examplare',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snakes.snake'),
        ),
    ]
