# Generated by Django 3.1.3 on 2020-11-07 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SnakeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='snakes.family')),
            ],
        ),
        migrations.CreateModel(
            name='Snake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.PositiveIntegerField(null=True)),
                ('is_poison', models.BooleanField(default=True)),
                ('card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snakes.snakecard')),
                ('food', models.ManyToManyField(to='snakes.Food')),
                ('specia', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='snakes.specia')),
            ],
        ),
    ]
