# Generated by Django 3.1.3 on 2020-11-07 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0002_auto_20201107_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snake',
            name='food',
        ),
        migrations.AddField(
            model_name='snake',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snakes.food'),
        ),
    ]
