# Generated by Django 3.1.3 on 2020-11-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0003_auto_20201107_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snake',
            name='food',
        ),
        migrations.AddField(
            model_name='snake',
            name='food',
            field=models.ManyToManyField(blank=True, null=True, to='snakes.Food'),
        ),
    ]
