# Generated by Django 3.1.3 on 2020-11-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0004_auto_20201107_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='snake',
            name='food',
            field=models.ManyToManyField(blank=True, to='snakes.Food'),
        ),
    ]
