# Generated by Django 3.1.3 on 2020-11-07 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0005_auto_20201107_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snakecard',
            name='examplare',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snakes.snake'),
        ),
    ]
