# Generated by Django 3.1.3 on 2020-11-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0007_auto_20201107_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snake',
            name='food',
        ),
        migrations.RemoveField(
            model_name='snake',
            name='is_poison',
        ),
        migrations.AddField(
            model_name='specia',
            name='food',
            field=models.ManyToManyField(blank=True, to='snakes.Food'),
        ),
        migrations.AddField(
            model_name='specia',
            name='is_poison',
            field=models.BooleanField(default=True),
        ),
    ]
