# Generated by Django 3.1.3 on 2020-11-07 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0008_auto_20201107_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='snakecard',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snakecard',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
