# Generated by Django 3.1.3 on 2020-11-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0013_snake_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='snakecard',
            name='create_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
