# Generated by Django 3.1.3 on 2020-11-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snake',
            name='food',
            field=models.TextField(null=True),
        ),
    ]
