# Generated by Django 3.1.3 on 2020-11-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakes', '0002_auto_20201104_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snake',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='snake',
            name='is_poison',
            field=models.BooleanField(default=True),
        ),
    ]
