# Generated by Django 3.1 on 2020-10-27 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20201027_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
