# Generated by Django 3.1 on 2020-10-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='food',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
